# Labels are set to add information in file like
# who wrote this file his email and contact details
# env variables will used to provide environment variables
# using env variable we will create file 

FROM ubuntu
RUN apt-get update
LABEL name="ommore"
LABEL email="omemail@gmail.com"
ENV filename=samplefile
RUN touch $filename