# we will see how can i ssh to docker container from 
# my docker host (docker installed machine)
# Not from another machine
# If you want to do from another machine, you can map port using 
# -p <machine_port>:<container_port>

FROM ubuntu
RUN apt-get update -y
RUN apt-get install openssh-server -y
RUN apt-get install openssh-client -y
RUN mkdir -p /var/run/sshd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]